package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverPosition<M extends BaseDriverPosition<M>> extends Model<M> implements IBean {

	public void setPositionId(java.lang.String positionId) {
		set("positionId", positionId);
	}

	public java.lang.String getPositionId() {
		return get("positionId");
	}

	public void setDriverId(java.lang.Integer driverId) {
		set("driverId", driverId);
	}

	public java.lang.Integer getDriverId() {
		return get("driverId");
	}

	public void setLon(java.lang.Double lon) {
		set("lon", lon);
	}

	public java.lang.Double getLon() {
		return get("lon");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}

	public java.lang.Double getLat() {
		return get("lat");
	}

	public void setPositionTime(java.util.Date positionTime) {
		set("positionTime", positionTime);
	}

	public java.util.Date getPositionTime() {
		return get("positionTime");
	}

}
