package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCancelOrder<M extends BaseCancelOrder<M>> extends Model<M> implements IBean {

	public void setCancelOrderId(java.lang.Integer cancelOrderId) {
		set("cancelOrderId", cancelOrderId);
	}

	public java.lang.Integer getCancelOrderId() {
		return get("cancelOrderId");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancelTime", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancelTime");
	}

}
