package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChangePhone<M extends BaseChangePhone<M>> extends Model<M> implements IBean {

	public void setChangePhoneId(java.lang.Integer changePhoneId) {
		set("changePhoneId", changePhoneId);
	}

	public java.lang.Integer getChangePhoneId() {
		return get("changePhoneId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setChangePhoneTime(java.util.Date changePhoneTime) {
		set("changePhoneTime", changePhoneTime);
	}

	public java.util.Date getChangePhoneTime() {
		return get("changePhoneTime");
	}

}
