package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserPhone(java.lang.String userPhone) {
		set("userPhone", userPhone);
	}

	public java.lang.String getUserPhone() {
		return get("userPhone");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setIDcard(java.lang.String IDcard) {
		set("IDcard", IDcard);
	}

	public java.lang.String getIDcard() {
		return get("IDcard");
	}

	public void setUserRole(java.lang.Integer userRole) {
		set("userRole", userRole);
	}

	public java.lang.Integer getUserRole() {
		return get("userRole");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("headImg");
	}

	public void setUserMoney(java.lang.Double userMoney) {
		set("userMoney", userMoney);
	}

	public java.lang.Double getUserMoney() {
		return get("userMoney");
	}

	public void setAcceptState(java.lang.Integer AcceptState) {
		set("AcceptState", AcceptState);
	}

	public java.lang.Integer getAcceptState() {
		return get("AcceptState");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

}
