package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setHelpPersonPhone(java.lang.String helpPersonPhone) {
		set("helpPersonPhone", helpPersonPhone);
	}

	public java.lang.String getHelpPersonPhone() {
		return get("helpPersonPhone");
	}

	public void setWhoPay(java.lang.Integer whoPay) {
		set("whoPay", whoPay);
	}

	public java.lang.Integer getWhoPay() {
		return get("whoPay");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
	}

	public java.lang.Integer getOrderType() {
		return get("orderType");
	}

	public void setOrderState(java.lang.Integer orderState) {
		set("orderState", orderState);
	}

	public java.lang.Integer getOrderState() {
		return get("orderState");
	}

	public void setCommentState(java.lang.Integer commentState) {
		set("commentState", commentState);
	}

	public java.lang.Integer getCommentState() {
		return get("commentState");
	}

	public void setUserDeleteState(java.lang.Integer userDeleteState) {
		set("userDeleteState", userDeleteState);
	}

	public java.lang.Integer getUserDeleteState() {
		return get("userDeleteState");
	}

	public void setDriverDeleteState(java.lang.Integer driverDeleteState) {
		set("driverDeleteState", driverDeleteState);
	}

	public java.lang.Integer getDriverDeleteState() {
		return get("driverDeleteState");
	}

	public void setAddOrderTime(java.util.Date addOrderTime) {
		set("addOrderTime", addOrderTime);
	}

	public java.util.Date getAddOrderTime() {
		return get("addOrderTime");
	}

	public void setStartPlaceLon(java.lang.Double startPlaceLon) {
		set("startPlaceLon", startPlaceLon);
	}

	public java.lang.Double getStartPlaceLon() {
		return get("startPlaceLon");
	}

	public void setStartPlaceLat(java.lang.Double startPlaceLat) {
		set("startPlaceLat", startPlaceLat);
	}

	public java.lang.Double getStartPlaceLat() {
		return get("startPlaceLat");
	}

	public void setStartPlaceName(java.lang.String startPlaceName) {
		set("startPlaceName", startPlaceName);
	}

	public java.lang.String getStartPlaceName() {
		return get("startPlaceName");
	}

	public void setStartPlaceAddress(java.lang.String startPlaceAddress) {
		set("startPlaceAddress", startPlaceAddress);
	}

	public java.lang.String getStartPlaceAddress() {
		return get("startPlaceAddress");
	}

	public void setDriveEndLon(java.lang.Double driveEndLon) {
		set("driveEndLon", driveEndLon);
	}

	public java.lang.Double getDriveEndLon() {
		return get("driveEndLon");
	}

	public void setDriveEndlat(java.lang.Double driveEndlat) {
		set("driveEndlat", driveEndlat);
	}

	public java.lang.Double getDriveEndlat() {
		return get("driveEndlat");
	}

	public void setDriveEndName(java.lang.String driveEndName) {
		set("driveEndName", driveEndName);
	}

	public java.lang.String getDriveEndName() {
		return get("driveEndName");
	}

	public void setDriveEndAddress(java.lang.String driveEndAddress) {
		set("driveEndAddress", driveEndAddress);
	}

	public java.lang.String getDriveEndAddress() {
		return get("driveEndAddress");
	}

	public void setOrderDistance(java.lang.Double orderDistance) {
		set("orderDistance", orderDistance);
	}

	public java.lang.Double getOrderDistance() {
		return get("orderDistance");
	}

	public void setDriveMoney(java.lang.Double driveMoney) {
		set("driveMoney", driveMoney);
	}

	public java.lang.Double getDriveMoney() {
		return get("driveMoney");
	}

	public void setReportOrderUserPhone(java.lang.String reportOrderUserPhone) {
		set("reportOrderUserPhone", reportOrderUserPhone);
	}

	public java.lang.String getReportOrderUserPhone() {
		return get("reportOrderUserPhone");
	}

	public void setDriverId(java.lang.Integer driverId) {
		set("driverId", driverId);
	}

	public java.lang.Integer getDriverId() {
		return get("driverId");
	}

	public void setAcceptOrderLon(java.lang.Double acceptOrderLon) {
		set("acceptOrderLon", acceptOrderLon);
	}

	public java.lang.Double getAcceptOrderLon() {
		return get("acceptOrderLon");
	}

	public void setAcceptOrderLat(java.lang.Double acceptOrderLat) {
		set("acceptOrderLat", acceptOrderLat);
	}

	public java.lang.Double getAcceptOrderLat() {
		return get("acceptOrderLat");
	}

	public void setAcceptOrderTime(java.util.Date acceptOrderTime) {
		set("acceptOrderTime", acceptOrderTime);
	}

	public java.util.Date getAcceptOrderTime() {
		return get("acceptOrderTime");
	}

	public void setStartPlaceDistance(java.lang.Double startPlaceDistance) {
		set("startPlaceDistance", startPlaceDistance);
	}

	public java.lang.Double getStartPlaceDistance() {
		return get("startPlaceDistance");
	}

	public void setStartPlaceMoney(java.lang.Double startPlaceMoney) {
		set("startPlaceMoney", startPlaceMoney);
	}

	public java.lang.Double getStartPlaceMoney() {
		return get("startPlaceMoney");
	}

	public void setWaitStartTime(java.util.Date waitStartTime) {
		set("waitStartTime", waitStartTime);
	}

	public java.util.Date getWaitStartTime() {
		return get("waitStartTime");
	}

	public void setWaitEndTime(java.util.Date waitEndTime) {
		set("waitEndTime", waitEndTime);
	}

	public java.util.Date getWaitEndTime() {
		return get("waitEndTime");
	}

	public void setWaitMoney(java.lang.Double waitMoney) {
		set("waitMoney", waitMoney);
	}

	public java.lang.Double getWaitMoney() {
		return get("waitMoney");
	}

	public void setDriveEndTime(java.util.Date driveEndTime) {
		set("driveEndTime", driveEndTime);
	}

	public java.util.Date getDriveEndTime() {
		return get("driveEndTime");
	}

	public void setExtraMoney(java.lang.Double extraMoney) {
		set("extraMoney", extraMoney);
	}

	public java.lang.Double getExtraMoney() {
		return get("extraMoney");
	}

	public void setDriveTotalMoney(java.lang.Double driveTotalMoney) {
		set("driveTotalMoney", driveTotalMoney);
	}

	public java.lang.Double getDriveTotalMoney() {
		return get("driveTotalMoney");
	}

}
