package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(java.lang.Integer messageId) {
		set("messageId", messageId);
	}

	public java.lang.Integer getMessageId() {
		return get("messageId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msgContent", msgContent);
	}

	public java.lang.String getMsgContent() {
		return get("msgContent");
	}

	public void setMsgTime(java.util.Date msgTime) {
		set("msgTime", msgTime);
	}

	public java.util.Date getMsgTime() {
		return get("msgTime");
	}

	public void setRead(java.lang.Integer read) {
		set("read", read);
	}

	public java.lang.Integer getRead() {
		return get("read");
	}

}
