package model.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setCommentId(java.lang.Integer commentId) {
		set("commentId", commentId);
	}

	public java.lang.Integer getCommentId() {
		return get("commentId");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}

	public java.lang.Integer getGrade() {
		return get("grade");
	}

	public void setGradeTime(java.util.Date gradeTime) {
		set("gradeTime", gradeTime);
	}

	public java.util.Date getGradeTime() {
		return get("gradeTime");
	}

}
