package model.dao;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_admin", "id", Admin.class);
		arp.addMapping("t_cancel_order", "cancelOrderId", CancelOrder.class);
		arp.addMapping("t_change_phone", "changePhoneId", ChangePhone.class);
		arp.addMapping("t_comment", "commentId", Comment.class);
		arp.addMapping("t_driver_position", "positionId", DriverPosition.class);
		arp.addMapping("t_message", "messageId", Message.class);
		arp.addMapping("t_order", "orderId", Order.class);
		arp.addMapping("t_tree", "id", Tree.class);
		arp.addMapping("t_user", "userId", User.class);
		arp.addMapping("tmenu", "id", Tmenu.class);
	}
}

