package model.dao;

import java.util.HashMap;

import model.dao.inter.BaseModel;
import model.entity.BaseAskCash;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AskCash extends BaseAskCash<AskCash> implements BaseModel  {
	public static final AskCash dao = new AskCash();

	@Override
	public Object addDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object deleteDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object updateDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object getDataList(HashMap<String, Object> where) {
		return null;
	}

}
