package model.dao;

import java.util.HashMap;

import model.dao.inter.BaseModel;
import model.entity.BaseCancelOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CancelOrder extends BaseCancelOrder<CancelOrder> implements BaseModel  {
	public static final CancelOrder dao = new CancelOrder();

	@Override
	public Object addDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object deleteDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object updateDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object getDataList(HashMap<String, Object> where) {
		return null;
	}

}
