package model.dao;

import java.util.List;

import model.entity.BaseComment;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment();
	
	public enum OrderCommentStateEnum {
		未评论, 已评论
	}

	/**
	 * 计算该司机的评分
	 * @author wh
	 * @since 2016-12-21
	 * @param userId
	 * @return 
	 */
	public double findDriverGrade(String driverId) {
		String sql = "SELECT o.driverId,c.grade FROM t_order AS o LEFT JOIN" +
				" t_comment AS c ON o.orderId = c.orderId WHERE o.driverId =" +
				" ? AND c.commentId IS NOT NULL";
		List<Record> records = Db.find(sql, driverId);
		double gradeNum = records.size();
		double gradeCount = 0;
		// 该司机没有评论
		if(gradeNum == 0){
			return 5;
		}
		// 计算总分数
		for(Record record :records){
			gradeCount += record.getInt("grade") * 20;
		}
		
		double grade = (gradeCount / gradeNum) / 100 + 4;
		return grade;
	}
	
	public static void main(String[] args) {
		System.out.println((180 / 2) / 100.0);
	}
}
