package model.dao;

import model.entity.BaseTmenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tmenu extends BaseTmenu<Tmenu> {
	public static final Tmenu dao = new Tmenu();
}
