package model.dao;

import java.util.HashMap;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import model.dao.inter.BaseModel;
import model.entity.BaseTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tree extends BaseTree<Tree> implements BaseModel {
	public static final Tree dao = new Tree();
	
	@Override
	public Object addDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object deleteDate(HashMap<String, Object> where) {
		return null;
	}

	@Override
	public Object updateDate(HashMap<String, Object> where) {
		return null;
	}
	
	@Override
	public Object getDataList(HashMap<String, Object> where) {
		return null;
	}

	public List<Record> findAll() {
		String sql = "select * from t_tree where level = 2";
		return Db.find(sql);
	}

	
	public Record findTree(Object object) {
		String sql = "select * from t_tree where treeId = ?";
		return Db.findFirst(sql, object);
	}


	public List<Tree> findByLevel(int l) {
		String sql = "select * from t_tree where plevel = ?";
		return this.find(sql, l);
	}


	public List<Tree> findLow(Integer plevel) {
		String sql = "SELECT * from t_tree WHERE plevel = ?";
		return this.find(sql, plevel);
	}


}
